package com.dravenmiller.overseersterminal.ui.tabs

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.dravenmiller.overseersterminal.components.PipText
import com.dravenmiller.overseersterminal.components.VaultBoyAnimator
import com.dravenmiller.overseersterminal.theme.ThemeController
import com.dravenmiller.overseersterminal.health.BiometricBridge
import kotlinx.coroutines.launch
import overseersterminal.composeapp.generated.resources.* // Auto-generated by KMP

@Composable
fun StatusSubTab(themeController: ThemeController, biometricBridge: BiometricBridge?) {
    val coroutineScope = rememberCoroutineScope()
    var hpScore by remember { mutableStateOf(100) }
    var apScore by remember { mutableStateOf(100) }
    var terminalLog by remember { mutableStateOf("SYSTEM READY") }

    val vaultDwellerWalk = listOf(
        Res.drawable.walking_1,
        Res.drawable.walking_2,
        Res.drawable.walking_3,
        Res.drawable.walking_4,
        Res.drawable.walking_5,
        Res.drawable.walking_6,
        Res.drawable.walking_7,
        Res.drawable.walking_8,
    )


    LaunchedEffect(Unit) {
        if (biometricBridge != null) {
            hpScore = biometricBridge.getSleepHpScore()
            apScore = biometricBridge.getHeartRateApScore()
        }
    }

    Column(modifier = Modifier.fillMaxSize()) {

        // --- 1. THE VAULT BOY HOLOGRAM ---
        Box(
            modifier = Modifier.weight(1f).fillMaxWidth(),
            contentAlignment = Alignment.Center
        ) {
            VaultBoyAnimator(
                frames = vaultDwellerWalk,
                themeController = themeController,
                modifier = Modifier.size(200.dp) // Adjust size as needed!
            )
        }

        // --- 2. THE TERMINAL LOG ---
        Box(modifier = Modifier.fillMaxWidth().padding(start = 8.dp, end = 8.dp, bottom = 8.dp), contentAlignment = Alignment.CenterEnd) {
            PipText(text = "> $terminalLog", themeController = themeController, fontSize = 12.sp)
        }

        // --- 3. THE BUTTONS ---
        Row(
            modifier = Modifier.fillMaxWidth().padding(start = 8.dp, end = 8.dp, bottom = 4.dp),
            horizontalArrangement = Arrangement.End
        ) {
            PipText("[ LINK BIOMETRICS ]", themeController, fontSize = 12.sp, modifier = Modifier.clickable {
                if (biometricBridge == null) terminalLog = "ERR: NO HARDWARE" else biometricBridge.requestPermissions()
            }.padding(end = 16.dp))

            PipText("[ SYNC ]", themeController, fontSize = 12.sp, modifier = Modifier.clickable {
                if (biometricBridge == null) terminalLog = "ERR: NO HARDWARE" else {
                    terminalLog = "SCANNING VITALS..."
                    coroutineScope.launch {
                        hpScore = biometricBridge.getSleepHpScore()
                        apScore = biometricBridge.getHeartRateApScore()
                        terminalLog = "SYNC COMPLETE"
                    }
                }
            })
        }

        // --- 4. THE BARS ---
        Row(
            modifier = Modifier.fillMaxWidth().padding(top = 8.dp, bottom = 8.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.Bottom
        ) {
            // LEFT SIDE: HP
            Column(modifier = Modifier.weight(0.45f)) {
                PipText("HP $hpScore/100", themeController, fontSize = 14.sp)
                Box(modifier = Modifier.fillMaxWidth().height(14.dp).padding(top = 4.dp).background(Color.Red)) {
                    val hpFraction = (hpScore / 100f).coerceIn(0.01f, 1f)
                    Box(modifier = Modifier.fillMaxWidth(fraction = hpFraction).fillMaxHeight().background(themeController.activeColor))
                }
            }

            Spacer(modifier = Modifier.weight(0.1f))

            // RIGHT SIDE: AP
            Column(modifier = Modifier.weight(0.45f), horizontalAlignment = Alignment.End) {
                PipText("AP $apScore/100", themeController, fontSize = 14.sp)
                Box(modifier = Modifier.fillMaxWidth().height(14.dp).padding(top = 4.dp).background(Color.Black), contentAlignment = Alignment.CenterEnd) {
                    val apFraction = (apScore / 100f).coerceIn(0.01f, 1f)
                    Box(modifier = Modifier.fillMaxWidth(fraction = apFraction).fillMaxHeight().background(themeController.activeColor))
                }
            }
        }
    }
}
